# Generated by Django 2.0.6 on 2019-10-30 23:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do curso')),
                ('carga_horaria', models.TimeField(verbose_name='Carga Horária')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('valor', models.FloatField(verbose_name='Valor Total')),
            ],
            options={
                'verbose_name': 'Curso Disponível',
                'verbose_name_plural': 'Cursos Disponíveis',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('fone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('valor', models.FloatField(verbose_name='Valor h/a')),
            ],
            options={
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Ident. Turma')),
                ('datainicio', models.DateField(verbose_name='Data Inicio')),
                ('datatermino', models.DateField(verbose_name='Data Termino')),
                ('horainicio', models.TimeField(verbose_name='Hora Inicio')),
                ('horatermino', models.TimeField(verbose_name='Hora Termino')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor')),
            ],
            options={
                'verbose_name_plural': 'Turmas',
                'ordering': ('-datainicio', 'horainicio'),
            },
        ),
    ]
